### ISSUE TITLE
Update README.md's "What's installed" to PHP 7.0

### ISSUE THREAD

**Issue by jgraup** [ideasonpurpose/basic-wordpress-box#13]
[What's Installed](https://github.com/ideasonpurpose/basic-wordpress-box/blob/php7/README.md#whats-installed) should be updated to PHP 7.0.x per your [commit](https://github.com/ideasonpurpose/basic-wordpress-box/commit/136f6f4f2774b653120c4495f4ecd876824b1896#diff-33407f429aebe761aa6cfdcfc912a2f6R8) on the [php7](https://github.com/ideasonpurpose/basic-wordpress-box/tree/php7) branch.

**Comment by joemaller** [comment]
Closed by 7bef0dac96a5c2f99254f053f3a6d5514827577e
