### ISSUE TITLE
PHP 5.5 EOL

### ISSUE THREAD

**Issue by jgraup** [ideasonpurpose/basic-wordpress-box#14]
[PHP 5.5](https://github.com/ideasonpurpose/basic-wordpress-box/blob/master/ansible/roles/php/tasks/php5.yml#L6) EOL was about 3 months ago now - 21 Jul 2016. http://php.net/eol.php.

Consider making [PHP 5.6](https://github.com/ideasonpurpose/basic-wordpress-box/blob/master/ansible/roles/php/tasks/php5.yml#L7) the default.

**Comment by joemaller** [comment]
I was holding out for WP Engine to upgrade (they're still running 5.5.9) but I agree this needs to happen. Will be jumping directly to PHP 7.

**Comment by jgraup** [comment]
Would you mind making the 5.6 change just so I can see how you did it ;) Looks like it's a simple [uncomment](https://github.com/ideasonpurpose/basic-wordpress-box/blob/master/ansible/roles/php/tasks/php5.yml#L7) (unless it's not) but it would pair with some servers I have currently have. Keep in mind I realize it's extra work for you but would benefit to those looking through commit history -- at least for the next [2 years+2months](http://php.net/supported-versions.php) or so.

**Comment by jgraup** [comment]
Looks like this is literally [uncommenting](https://github.com/ideasonpurpose/basic-wordpress-box/blob/master/ansible/roles/php/tasks/php5.yml#L7) out the **php5-5.6** line and [rebuilding](https://github.com/ideasonpurpose/basic-wordpress-box/blob/master/build.sh) the box. Resulting in `$ php --version` -> `PHP 5.6.23-1+deprecated+dontuse+deb.sury.org~trusty+1 (cli)`.

To test locally, add the local file to Vagrant's boxes
`vagrant box add custom-basic-box file://${PWD}/virtualbox-basic-wp.box`

And then reference the box later in the [Vagrantfile](https://github.com/ideasonpurpose/basic-wordpress-vagrant/blob/master/Vagrantfile#L18) (excluding any [versions](https://github.com/ideasonpurpose/basic-wordpress-vagrant/blob/master/Vagrantfile#L19) in the configure)

```
Vagrant.configure(2) do |config|
  config.vm.box = "custom-basic-box"
  config.vm.hostname = $hostname
  config.vm.network "private_network", type: "dhcp"
```

**Comment by joemaller** [comment]
Nothing's ever simple 😩  The PHP PPA was revised since I last checked. It looks cleaner and easier, but it changes things. Testing today
