### ISSUE TITLE
Consider adding a flag in build.sh to auto add/remove the Vagrant box

### ISSUE THREAD

**Issue by jgraup** [ideasonpurpose/basic-wordpress-box#15]
When testing the box, I find myself just adding the box directly. I'd rather group this in the [build.sh](https://github.com/ideasonpurpose/basic-wordpress-box/blob/master/build.sh) as a flag. One to remove the old box, then another to add the box. This could just be appended after the main functions have ran.

```
#!/usr/bin/env bash

# Usage:
#
#   ./build.sh --remove-vagrant-box="OLD BOX NAME" --add-vagrant-box="NEW BOX NAME"

for i in "$@"
do
case $i in
  --remove-vagrant-box=*)
  BOX="${i#*=}"
  if [ ! -z "$BOX" ]
      then
         echo -e "\n$ vagrant box remove ${BOX}\n"
  fi
  ;;

  --add-vagrant-box=*)
  BOX="${i#*=}"
  if [ ! -z "$BOX" ]
      then
         echo -e "\n$ vagrant box add ${BOX} file://${PWD}/virtualbox-basic-wp.box\n"
  fi
  ;;
esac
done
```

**Comment by jgraup** [comment]
After looking at [build.sh](github.com/ideasonpurpose/basic-wordpress-box/blob/master/build.sh) again, I see you already [--force](https://github.com/ideasonpurpose/basic-wordpress-box/blob/master/build.sh#L14) the box to be added. I wonder if it's beneficial to allow for an alternate name.

**Comment by joemaller** [comment]
My thinking around building new base boxes is that the box is an artifact which is constantly being recreated. After running the build script, the resulting box is added to Vagrant and ready to be spun up. Usually my process is to build the box, then `vagrant destroy -f && vagrant up
` a separate project using the new, local box.  Terminal history ends up full of this:

presumably, a rollback should be possible by just checking out a previous Git commit.

**Comment by joemaller** [comment]
I'm pretty happy with how this is working right now. This feature should be pretty easy to implement on a fork, but it's not something I want to add to the project.

**Comment by jgraup** [comment]
I agree. My hope is that any customization would only require a couple external .sh files anyway rather than a full fork because you seem to have everything covered.
