### ISSUE TITLE
Update to wp-cli 1.1.0

### ISSUE THREAD

**Issue by joemaller** [ideasonpurpose/basic-wordpress-box#20]
http://wp-cli.org/blog/version-1.0.0.html

**Comment by joemaller** [comment]
Might as well enable `debug` verbosity in the config file while we're at it. 

https://wp-cli.org/config/

**Comment by jgraup** [comment]
Looks like 1.1.0 is the latest now - https://make.wordpress.org/cli/2017/02/01/version-1-1-0/

**Comment by joemaller** [comment]
This is now updated whenever the box is. Current release includes `WP-CLI 1.4.0`
